import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer';
import Header from '../components/Header';
import Form from '../components/Form';
import Link from 'next/link';
import { Alert } from '../components/Alert';

export default function Home() {
  return (
    <div className={styles.container} data-theme="wireframe">
      <Head>
        <title>Realtime On-Chain Notifications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Alert />

      <Header />

      <div className="hero min-h-screen bg-base-200">
        <div className="hero-content flex-col lg:flex-row-reverse">
          <ul className="steps steps-vertical m-auto w-1/2">
            <li className="step step-primary">Connect Wallet</li>
            <li className="step">Save Notify Device</li>
            <li className="step">Subscribe Event</li>
            <li className="step">Wait for Notifications</li>
          </ul>
          <div>
            <h1 className="text-5xl font-bold">Realtime On-Chain Notifications!</h1>
            <p className="py-4">Basic Algorand On-chain Notifications for gitcoin hackathon - ayden lee</p>
            <Link href="#form">
              <label className="btn btn-primary modal-button">Get Started</label>
            </Link>
          </div>
        </div>
      </div>

      <Form />

      <Footer />
    </div >
  )
}
